version: '3.4'

volumes:
    mongodb-sigmf-volume:
    opensearch-data1:

services:
    monstache:        
        image: rwynn/monstache:latest        
        container_name: monstache     
        working_dir: /monstache        
        command: -f ./config.toml        
        volumes:          
            - ./monstache:/monstache/       
        ports:          
            - 8080:8080     
        restart: always

    mongo-sigmf:
        build:
            context: ./mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_REPLICA_SET_NAME=rs0
        volumes:
            - mongodb-sigmf-volume:/data/db'
        ports:
            - 27017:27017
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u admin -p admin --quiet) -eq 1
            interval: 10s
            start_period: 30s

    # web application to inspect the sigmf mongodb
    mongo-express:
        image: mongo-express
        container_name: mexpress
        depends_on:
            - mongo-sigmf
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongo-sigmf:27017/?authSource=admin
            - ME_CONFIG_BASICAUTH_USERNAME=sigence
            - ME_CONFIG_BASICAUTH_PASSWORD=sigence
        restart: unless-stopped
        ports:
            - "8082:8081"

    opensearch-node1:
        image: opensearchproject/opensearch:latest
        container_name: opensearch-node1
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node1
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
            - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
            - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
            - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - opensearch-data1:/usr/share/opensearch/data
        ports:
            - 9200:9200
            - 9600:9600 # required for Performance Analyzer
